### ISSUE TITLE
Preferences & Status

### ISSUE THREAD

**Issue by atton16** [gmontalvoriv/mongod-starter#1]
Hi,

It is a great program. I was thinking about writing my own before I found yours.

One thing though. In order to access directory like /usr/local using Finder interface, you have to either turn on hidden folders or make an alias to the folder to each of the path locations.

This makes it very hard for user that install MongoDB via Homebrew like me to do the configurations even though the configuration only requires you to do it once.

It would be great if I can manually type in the path or copy and paste those paths directly to the input box, or better, the program can intelligently scan for MongoDB and it's files for Homebrew users.

Additionally, the apps would be perfect if the app icon changes when MongoDB instance is running/not running.

If you like, I can help collaborate that get it improved.

Cheers,
Attawit

**Comment by gmontalvoriv** [comment]
Hello Attawit,

I’m very glad you liked the project. You pointed out some great features that could definitely improve the user experience. I haven’t had the time to work on this project lately so it would be great if you could collaborate to continue to improve it. I will add you as a collaborator.
